// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPNELM36DO-RKKz8t7UGzej_fauk1NcPI',
    appId: '1:361604759879:android:be4f25ee1023e22af70c62',
    messagingSenderId: '361604759879',
    projectId: 'flow-ba009',
    storageBucket: 'flow-ba009.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6u72_hmJRjy6oW6ERJZKLp4D2apeNfvk',
    appId: '1:361604759879:ios:cbefa52658dc20dff70c62',
    messagingSenderId: '361604759879',
    projectId: 'flow-ba009',
    storageBucket: 'flow-ba009.appspot.com',
    iosBundleId: 'com.example.flow',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE24GHQ_Z06uds_iGQVG7dP4ItfbgupKg',
    appId: '1:361604759879:web:f6d727dd0ef253fff70c62',
    messagingSenderId: '361604759879',
    projectId: 'flow-ba009',
    authDomain: 'flow-ba009.firebaseapp.com',
    storageBucket: 'flow-ba009.appspot.com',
    measurementId: 'G-1ZKG4QW6PE',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6u72_hmJRjy6oW6ERJZKLp4D2apeNfvk',
    appId: '1:361604759879:ios:cbefa52658dc20dff70c62',
    messagingSenderId: '361604759879',
    projectId: 'flow-ba009',
    storageBucket: 'flow-ba009.appspot.com',
    iosBundleId: 'com.example.flow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAE24GHQ_Z06uds_iGQVG7dP4ItfbgupKg',
    appId: '1:361604759879:web:8d6988c5a356af55f70c62',
    messagingSenderId: '361604759879',
    projectId: 'flow-ba009',
    authDomain: 'flow-ba009.firebaseapp.com',
    storageBucket: 'flow-ba009.appspot.com',
    measurementId: 'G-4ZJMJ01MJG',
  );

}